/**
 * TypeScript type definitions for Flask API contracts
 * Types are now derived from Zod schemas for runtime validation
 * 
 * For schema definitions, see: schemas/api.ts
 */

// Re-export all types from schemas (which are inferred from Zod)
export type {
  UserContactInfo,
  ApiError,
  ResumeSummary,
  ResumeUploadResponse,
  ResumeUploadBackendResponse,
  Resume,
  ResumesResponse,
  JobTargetCreateRequest,
  JobTargetCreateResponse,
  GapRunRequest,
  GapRunResponse,
  SkillEvidence,
  MissingSkill,
  WeakSkill,
  GapReport,
  LearningGenerateRequest,
  LearningGenerateResponse,
  LearningItem,
  TasksAddRequest,
  TasksAddResponse,
  ExportParams,
  Job,
  JobsResponse,
  JobFilters,
  JobSearchResponse,
  JobCollectionsResponse,
  SaveJobResponse,
  JobSavedStatus,
  TaskNote,
  TaskGoal,
  TaskLearningItem,
  Task,
  TasksResponse,
  TaskCreateRequest,
  TaskUpdateRequest,
  TaskResponse,
  TaskDeleteResponse,
  TaskFilters,
  ApiResponse,
  ApiRequest,
} from '@/schemas/api';

// Also export schemas for runtime validation
export {
  UserContactInfoSchema,
  ApiErrorSchema,
  ResumeSummarySchema,
  ResumeUploadResponseSchema,
  ResumeUploadBackendResponseSchema,
  ResumeSchema,
  ResumesResponseSchema,
  JobTargetCreateRequestSchema,
  JobTargetCreateResponseSchema,
  GapRunRequestSchema,
  GapRunResponseSchema,
  SkillEvidenceSchema,
  MissingSkillSchema,
  WeakSkillSchema,
  GapReportSchema,
  LearningGenerateRequestSchema,
  LearningGenerateResponseSchema,
  LearningItemSchema,
  TasksAddRequestSchema,
  TasksAddResponseSchema,
  ExportParamsSchema,
  JobSchema,
  JobsResponseSchema,
  JobFiltersSchema,
  JobSearchResponseSchema,
  JobCollectionsResponseSchema,
  SaveJobResponseSchema,
  JobSavedStatusSchema,
  TaskNoteSchema,
  TaskGoalSchema,
  TaskLearningItemSchema,
  TaskPrioritySchema,
  TaskSchema,
  TasksResponseSchema,
  TaskCreateRequestSchema,
  TaskUpdateRequestSchema,
  TaskResponseSchema,
  TaskDeleteResponseSchema,
  TaskFiltersSchema,
} from '@/schemas/api';
