import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/shadcn-io/navbar";
import { auth0 } from "@/lib/auth0";
import { ReduxProvider } from "@/store/provider";
import { Toaster } from "@/components/ui/sonner";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased overscroll-y-none`}
      >
        <ReduxProvider>
          <div className="min-h-dvh grid grid-rows-[auto_1fr]">
            <Navbar
              userName={session?.user?.name ?? session?.user?.nickname}
              userEmail={session?.user?.email ?? undefined}
              userAvatar={session?.user?.picture ?? undefined}
            />
            <main className="min-h-0 overflow-y-auto overscroll-y-contain bg-surface">
              {children}
            </main>
          </div>
        </ReduxProvider>
        <Toaster />
      </body>
    </html>
  );
}
